#!/bin/bash

# ScOsf versions
mv "Proxima Nova ScOsf Extrabold Italic.otf" "ProximaNova-ScOsf-ExtraboldItalic.otf"
mv "Proxima Nova ScOsf Extrabold.otf" "ProximaNova-ScOsf-Extrabold.otf"
mv "Proxima Nova ScOsf Light Italic.otf" "ProximaNova-ScOsf-LightItalic.otf"
mv "Proxima Nova ScOsf Light.otf" "ProximaNova-ScOsf-Light.otf"
mv "Proxima Nova ScOsf Regular Italic.otf" "ProximaNova-ScOsf-RegularItalic.otf"
mv "Proxima Nova ScOsf Regular.otf" "ProximaNova-ScOsf-Regular.otf"
mv "Proxima Nova ScOsf Semibold Italic.otf" "ProximaNova-ScOsf-SemiboldItalic.otf"
mv "Proxima Nova ScOsf Semibold.otf" "ProximaNova-ScOsf-Semibold.otf"
mv "Proxima Nova ScOsf Thin Italic.otf" "ProximaNova-ScOsf-ThinItalic.otf"
mv "Proxima Nova ScOsf Thin.otf" "ProximaNova-ScOsf-Thin.otf"

# Condensed versions
mv "Proxima Nova Condensed Black.otf" "ProximaNova-Condensed-Black.otf"
mv "Proxima Nova Condensed Black Italic.otf" "ProximaNova-Condensed-BlackItalic.otf"
mv "Proxima Nova Condensed Bold.otf" "ProximaNova-Condensed-Bold.otf"
mv "Proxima Nova Condensed Bold Italic.otf" "ProximaNova-Condensed-BoldItalic.otf"
mv "Proxima Nova Condensed Extrabold.otf" "ProximaNova-Condensed-Extrabold.otf"
mv "Proxima Nova Condensed Extrabold Italic.otf" "ProximaNova-Condensed-ExtraboldItalic.otf"
mv "Proxima Nova Condensed Light.otf" "ProximaNova-Condensed-Light.otf"
mv "Proxima Nova Condensed Light Italic.otf" "ProximaNova-Condensed-LightItalic.otf"
mv "Proxima Nova Condensed Regular.otf" "ProximaNova-Condensed-Regular.otf"
mv "Proxima Nova Condensed Regular Italic.otf" "ProximaNova-Condensed-RegularItalic.otf"
mv "Proxima Nova Condensed Semibold.otf" "ProximaNova-Condensed-Semibold.otf"
mv "Proxima Nova Condensed Semibold Italic.otf" "ProximaNova-Condensed-SemiboldItalic.otf"
mv "Proxima Nova Condensed Thin.otf" "ProximaNova-Condensed-Thin.otf"
mv "Proxima Nova Condensed Thin Italic.otf" "ProximaNova-Condensed-ThinItalic.otf"

# Extra Condensed versions
mv "Proxima Nova Extra Condensed Black.otf" "ProximaNova-ExtraCondensed-Black.otf"
mv "Proxima Nova Extra Condensed Black Italic.otf" "ProximaNova-ExtraCondensed-BlackItalic.otf"
mv "Proxima Nova Extra Condensed Bold.otf" "ProximaNova-ExtraCondensed-Bold.otf"
mv "Proxima Nova Extra Condensed Bold Italic.otf" "ProximaNova-ExtraCondensed-BoldItalic.otf"
mv "Proxima Nova Extra Condensed Extrabold.otf" "ProximaNova-ExtraCondensed-Extrabold.otf"
mv "Proxima Nova Extra Condensed Extrabold Italic.otf" "ProximaNova-ExtraCondensed-ExtraboldItalic.otf"
mv "Proxima Nova Extra Condensed Light.otf" "ProximaNova-ExtraCondensed-Light.otf"
mv "Proxima Nova Extra Condensed Light Italic.otf" "ProximaNova-ExtraCondensed-LightItalic.otf"
mv "Proxima Nova Extra Condensed Regular.otf" "ProximaNova-ExtraCondensed-Regular.otf"
mv "Proxima Nova Extra Condensed Regular Italic.otf" "ProximaNova-ExtraCondensed-RegularItalic.otf"
mv "Proxima Nova Extra Condensed Semibold.otf" "ProximaNova-ExtraCondensed-Semibold.otf"
mv "Proxima Nova Extra Condensed Semibold Italic.otf" "ProximaNova-ExtraCondensed-SemiboldItalic.otf"
mv "Proxima Nova Extra Condensed Thin.otf" "ProximaNova-ExtraCondensed-Thin.otf"
mv "Proxima Nova Extra Condensed Thin Italic.otf" "ProximaNova-ExtraCondensed-ThinItalic.otf"
